# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
jobs:
  minify:
    runs-on: ubuntu-latest
    steps:
      - name: HTML/CSS/JS Minifier
        uses: devatherock/minify-js@v1.0.2
